version: '3.8'

services:
  app:
    build: .
    container_name: code-nest
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: nestpassword
      DATABASE_NAME: code-nest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['pnpm', 'run', 'start:dev']
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: nestjs-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: code-nest
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
