version: '3.8'

services:
  app:
    build: .
    container_name: code-nest
    restart: always
    ports:
      - '8000:3000'
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['pnpm', 'run', 'start:dev']
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: nest-db
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./dbdata/test:/var/lib/mysql

volumes:
  mysql-data:
